name: project_template
channels:
  - defaults
dependencies:
  - python
  - scikit-learn
  - pyarrow
  - r-base
  - r-arrow
  - r-dplyr
  - r-data.table
  - pandas
  - jupyterlab
  - r-irkernel
  - ipykernel

