name: project_template
channels:
  - r
  - conda-forge
  - defaults
dependencies:
  - _r-mutex
  - appnope
  - arrow-cpp
  - attrs
  - backcall
  - blas
  - bleach
  - boost-cpp
  - brotli
  - bwidget
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - cctools
  - certifi
  - clang
  - clang_osx-64
  - clangxx
  - clangxx_osx-64
  - compiler-rt
  - compiler-rt_osx-64
  - curl
  - decorator
  - defusedxml
  - double-conversion
  - entrypoints
  - fontconfig
  - freetype
  - fribidi
  - gettext
  - gflags
  - gfortran_osx-64
  - glib
  - glog
  - graphite2
  - grpc-cpp
  - gsl
  - harfbuzz
  - icu
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - jupyterlab_server
  - krb5
  - ld64
  - libboost
  - libcurl
  - libcxx
  - libcxxabi
  - libedit
  - libevent
  - libffi
  - libgfortran
  - libiconv
  - libllvm9
  - libpng
  - libprotobuf
  - libsodium
  - libssh2
  - libtiff
  - libxml2
  - llvm-openmp
  - lz4
  - lz4-c
  - make
  - markupsafe
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - nbconvert
  - nbformat
  - ncurses
  - notebook
  - numpy-base
  - openssl
  - pandas
  - pandoc
  - pandocfilters
  - pango
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pip
  - pixman
  - prometheus_client
  - prompt_toolkit
  - ptyprocess
  - pyarrow
  - pygments
  - pyrsistent
  - python
  - python-dateutil
  - pytz
  - pyzmq
  - r-arrow
  - r-assertthat
  - r-backports
  - r-base
  - r-base64enc
  - r-bh
  - r-bit
  - r-bit64
  - r-cli
  - r-crayon
  - r-data.table
  - r-digest
  - r-dplyr
  - r-ellipsis
  - r-evaluate
  - r-fansi
  - r-fs
  - r-glue
  - r-htmltools
  - r-irdisplay
  - r-irkernel
  - r-jsonlite
  - r-magrittr
  - r-pbdzmq
  - r-pillar
  - r-pkgconfig
  - r-plogr
  - r-purrr
  - r-r6
  - r-rcpp
  - r-repr
  - r-rlang
  - r-tibble
  - r-tidyselect
  - r-utf8
  - r-uuid
  - r-vctrs
  - r-zeallot
  - re2
  - readline
  - scikit-learn
  - scipy
  - send2trash
  - setuptools
  - six
  - snappy
  - sqlite
  - tapi
  - terminado
  - testpath
  - thrift-cpp
  - tk
  - tktable
  - tornado
  - traitlets
  - uriparser
  - wcwidth
  - webencodings
  - wheel
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - alembic
    - azure-common
    - azure-storage-blob
    - azure-storage-common
    - cffi
    - chardet
    - click
    - cloudpickle
    - configparser
    - cryptography
    - databricks-cli
    - docker
    - flask
    - gitdb
    - gitpython
    - gorilla
    - gunicorn
    - idna
    - itsdangerous
    - mako
    - mlflow
    - numpy
    - prometheus-flask-exporter
    - protobuf
    - pycparser
    - python-editor
    - pyyaml
    - querystring-parser
    - requests
    - simplejson
    - smmap
    - sqlalchemy
    - sqlparse
    - tabulate
    - urllib3
    - websocket-client
    - werkzeug

