name: project_template
channels:
  - r
  - conda-forge
  - defaults
dependencies:
  - _r-mutex=1.0.0
  - appnope=0.1.0
  - arrow-cpp=0.15.1
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.1
  - boost-cpp=1.69.0
  - brotli=1.0.7
  - bwidget=1.9.11
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2020.1.1
  - cairo=1.14.12
  - cctools=927.0.2
  - certifi=2019.11.28
  - clang=9.0.1
  - clang_osx-64=9.0.1
  - clangxx=9.0.1
  - clangxx_osx-64=9.0.1
  - compiler-rt=9.0.1
  - compiler-rt_osx-64=9.0.1
  - curl=7.67.0
  - decorator=4.4.1
  - defusedxml=0.6.0
  - double-conversion=3.1.5
  - entrypoints=0.3
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - gettext=0.19.8.1
  - gflags=2.2.2
  - gfortran_osx-64=4.8.5
  - glib=2.63.1
  - glog=0.4.0
  - graphite2=1.3.13
  - grpc-cpp=1.26.0
  - gsl=2.4
  - harfbuzz=1.8.8
  - icu=58.2
  - importlib_metadata=1.5.0
  - intel-openmp=2019.4
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - jedi=0.16.0
  - jinja2=2.11.1
  - joblib=0.14.1
  - jpeg=9b
  - json5=0.9.0
  - jsonschema=3.2.0
  - jupyter_client=6.0.0
  - jupyter_core=4.6.3
  - jupyterlab=1.2.6
  - jupyterlab_server=1.0.6
  - krb5=1.16.4
  - ld64=450.3
  - libboost=1.67.0
  - libcurl=7.67.0
  - libcxx=9.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libevent=2.1.10
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libllvm9=9.0.1
  - libpng=1.6.37
  - libprotobuf=3.11.2
  - libsodium=1.0.16
  - libssh2=1.8.2
  - libtiff=4.1.0
  - libxml2=2.9.9
  - llvm-openmp=4.0.1
  - lz4=3.0.2
  - lz4-c=1.8.3
  - make=4.2.1
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.2
  - notebook=6.0.3
  - numpy-base=1.18.1
  - openssl=1.1.1d
  - pandas=1.0.1
  - pandoc=2.9.2
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.6.1
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - pixman=0.38.0
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.3
  - ptyprocess=0.6.0
  - pyarrow=0.15.1
  - pygments=2.5.2
  - pyrsistent=0.15.7
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyzmq=17.1.2
  - r-arrow=0.15.1
  - r-assertthat=0.2.1
  - r-backports=1.1.5
  - r-base=3.6.1
  - r-base64enc=0.1_3
  - r-bh=1.69.0_1
  - r-bit=1.1_15.2
  - r-bit64=0.9_7
  - r-cli=1.1.0
  - r-crayon=1.3.4
  - r-data.table=1.12.2
  - r-digest=0.6.25
  - r-dplyr=0.8.0.1
  - r-ellipsis=0.3.0
  - r-evaluate=0.13
  - r-fansi=0.4.0
  - r-fs=1.3.1
  - r-glue=1.3.1
  - r-htmltools=0.3.6
  - r-irdisplay=0.7.0
  - r-irkernel=0.8.15
  - r-jsonlite=1.6
  - r-magrittr=1.5
  - r-pbdzmq=0.3_3
  - r-pillar=1.3.1
  - r-pkgconfig=2.0.2
  - r-plogr=0.2.0
  - r-purrr=0.3.3
  - r-r6=2.4.1
  - r-rcpp=1.0.3
  - r-repr=0.19.2
  - r-rlang=0.4.4
  - r-tibble=2.1.1
  - r-tidyselect=1.0.0
  - r-utf8=1.1.4
  - r-uuid=0.1_2
  - r-vctrs=0.2.3
  - r-zeallot=0.1.0
  - re2=2019.09.01
  - readline=7.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=45.2.0
  - six=1.14.0
  - snappy=1.1.7
  - sqlite=3.31.1
  - tapi=1000.10.8
  - terminado=0.8.3
  - testpath=0.4.4
  - thrift-cpp=0.11.0
  - tk=8.6.8
  - tktable=2.10
  - tornado=6.0.3
  - traitlets=4.3.3
  - uriparser=0.9.3
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.2
  - xz=5.2.4
  - zeromq=4.2.5
  - zipp=3.0.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - adal==1.2.2
    - alembic==1.4.0
    - applicationinsights==0.11.9
    - azure-common==1.1.24
    - azure-graphrbac==0.61.1
    - azure-mgmt-authorization==0.60.0
    - azure-mgmt-containerregistry==2.8.0
    - azure-mgmt-keyvault==2.1.1
    - azure-mgmt-resource==8.0.1
    - azure-mgmt-storage==7.2.0
    - azure-storage-blob==2.1.0
    - azure-storage-common==2.1.0
    - azureml-automl-core==1.0.85.5
    - azureml-core==1.0.85.5
    - azureml-dataprep==1.1.38
    - azureml-dataprep-native==13.2.0
    - azureml-pipeline==1.0.85
    - azureml-pipeline-core==1.0.85.1
    - azureml-pipeline-steps==1.0.85
    - azureml-sdk==1.0.85
    - azureml-telemetry==1.0.85.2
    - azureml-train==1.0.85
    - azureml-train-automl-client==1.0.85.4
    - azureml-train-core==1.0.85
    - azureml-train-restclients-hyperdrive==1.0.85
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - cffi==1.14.0
    - chardet==3.0.4
    - click==7.0
    - cloudpickle==1.3.0
    - configparser==4.0.2
    - contextlib2==0.6.0.post1
    - cryptography==2.8
    - databricks-cli==0.9.1
    - distro==1.4.0
    - docker==4.2.0
    - dotnetcore2==2.1.13
    - flake8==3.7.9
    - flask==1.1.1
    - fusepy==3.0.1
    - gitdb==4.0.2
    - gitpython==3.1.0
    - gorilla==0.3.0
    - gunicorn==20.0.4
    - idna==2.9
    - isodate==0.6.0
    - itsdangerous==1.1.0
    - jeepney==0.4.2
    - jmespath==0.9.5
    - jsonpickle==1.3
    - mako==1.1.1
    - mccabe==0.6.1
    - mlflow==1.6.0
    - msrest==0.6.11
    - msrestazure==0.6.2
    - ndg-httpsclient==0.5.1
    - numpy==1.18.1
    - oauthlib==3.1.0
    - pathspec==0.7.0
    - prometheus-flask-exporter==0.12.2
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pycodestyle==2.5.0
    - pycparser==2.19
    - pyflakes==2.1.1
    - pyjwt==1.7.1
    - pyopenssl==19.1.0
    - python-editor==1.0.4
    - pyyaml==5.3
    - querystring-parser==1.2.4
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - ruamel-yaml==0.15.89
    - secretstorage==3.1.2
    - simplejson==3.17.0
    - smmap==3.0.1
    - sqlalchemy==1.3.13
    - sqlparse==0.3.0
    - tabulate==0.8.6
    - urllib3==1.25.8
    - websocket-client==0.57.0
    - werkzeug==1.0.0

